[build]
  publish = "."
  functions = "netlify/functions"

# Rewrite /arinadress/images/* to /images/* (proxy compatible)
[[redirects]]
  from = "/arinadress/images/*"
  to = "/images/:splat"
  status = 200

# Rewrite /arinadress/fonts/* to /fonts/* (proxy compatible)
[[redirects]]
  from = "/arinadress/fonts/*"
  to = "/fonts/:splat"
  status = 200

# Rewrite /arinadress/ to index
[[redirects]]
  from = "/arinadress/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/arinadress"
  to = "/index.html"
  status = 200
